services:

  db:
    image: timescale/timescaledb:latest-pg16
    ports:
      - 5432:5432
    volumes:
      - ./volumes:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=smartcomplain

  api:
    image: hamelnhackt/backend-api:0.0.1
    ports:
      - 8000:8000

  frontend:
    image: hamelnhackt/frontend:0.0.1
    ports:
      - 9000:80
