FROM python:3.12

COPY api /app/api
COPY backend /app/backend
COPY ./requirements.txt /app/
RUN apt update && apt upgrade -y && apt install gcc -y
RUN pip install -r /app/requirements.txt

CMD ["python3", "/app/api/main.py"]