export DB_HOST="localhost"
export DB_PORT="15432"
export BACKEND_URL="http://localhost:8000"
export LLM_MODEL="http://localhost:11434/api/generate"
export IMG_CLASSES="tree, trees, street, road, playground, water"